// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCRjwMr6-9vtCHb6m9uvWHijsk4lxo24c',
    appId: '1:730429805990:web:a3ad2438a031032b69ab67',
    messagingSenderId: '730429805990',
    projectId: 'game-rev',
    authDomain: 'game-rev.firebaseapp.com',
    storageBucket: 'game-rev.appspot.com',
    measurementId: 'G-DXZSWB5F4D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaVzNaLKoVE_0ksUcLdShlxmLC1x7p5N0',
    appId: '1:730429805990:android:377afdbb8701d80369ab67',
    messagingSenderId: '730429805990',
    projectId: 'game-rev',
    storageBucket: 'game-rev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoPVwHxKuNR17LfVPI4OVMmSkILv4DjfQ',
    appId: '1:730429805990:ios:0ecc6cee3990ebe869ab67',
    messagingSenderId: '730429805990',
    projectId: 'game-rev',
    storageBucket: 'game-rev.appspot.com',
    iosClientId: '730429805990-ntlgjrup8fl4cp200g3htotr59cds9h4.apps.googleusercontent.com',
    iosBundleId: 'com.brainbytelabs.gamerev.gameRev',
  );
}
